<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Location;

class LocationSeeder extends Seeder
{
    public function run()
    {
        $locations = [
            [
                'name' => 'Kawah Putih',
                'description' => 'Danau vulkanik dengan air berwarna putih kehijauan yang dikelilingi oleh pegunungan, menciptakan pemandangan yang menakjubkan.',
                'latitude' => -7.1661,
                'longitude' => 107.4027,
                'status' => 'approved',
                'user_id' => 1,
                'category' => 'Alam',
                'rating' => 4.7,
                'reviews_count' => 250,
                'address' => 'Ciwidey, Kabupaten Bandung, Jawa Barat',
                'image_url' => 'https://picsum.photos/200/300?random=1',
            ],
            [
                'name' => 'Situ Patenggang',
                'description' => 'Danau alami yang berada di ketinggian dengan pemandangan perkebunan teh yang indah dan udara yang sejuk.',
                'latitude' => -7.1665,
                'longitude' => 107.3577,
                'status' => 'approved',
                'user_id' => 1,
                'category' => 'Alam',
                'rating' => 4.6,
                'reviews_count' => 180,
                'address' => 'Ciwidey, Kabupaten Bandung, Jawa Barat',
                'image_url' => 'https://picsum.photos/200/300?random=2',
            ],
            [
                'name' => 'Kampung Cai Ranca Upas',
                'description' => 'Tempat wisata alam yang terkenal dengan penangkaran rusa, area perkemahan, dan pemandangan hijau yang asri.',
                'latitude' => -7.1601,
                'longitude' => 107.4013,
                'status' => 'approved',
                'user_id' => 1,
                'category' => 'Rekreasi',
                'rating' => 4.8,
                'reviews_count' => 300,
                'address' => 'Ciwidey, Kabupaten Bandung, Jawa Barat',
                'image_url' => 'https://picsum.photos/200/300?random=3',
            ],
            [
                'name' => 'Dusun Bambu',
                'description' => 'Tempat wisata yang menggabungkan alam, budaya, dan kuliner dengan suasana pedesaan yang nyaman.',
                'latitude' => -6.7954,
                'longitude' => 107.5921,
                'status' => 'approved',
                'user_id' => 1,
                'category' => 'Rekreasi',
                'rating' => 4.5,
                'reviews_count' => 220,
                'address' => 'Lembang, Kabupaten Bandung, Jawa Barat',
                'image_url' => 'https://picsum.photos/200/300?random=4',
            ],
            [
                'name' => 'Trans Studio Bandung',
                'description' => 'Taman hiburan indoor terbesar di Indonesia yang menawarkan berbagai wahana dan atraksi seru untuk keluarga.',
                'latitude' => -6.9254,
                'longitude' => 107.6345,
                'status' => 'approved',
                'user_id' => 1,
                'category' => 'Hiburan',
                'rating' => 4.7,
                'reviews_count' => 500,
                'address' => 'Jl. Gatot Subroto, Bandung, Jawa Barat',
                'image_url' => 'https://picsum.photos/200/300?random=5',
            ],
            [
                'name' => 'Curug Malela',
                'description' => 'Air terjun yang dijuluki "Niagara Mini" di Jawa Barat, dengan aliran air yang deras dan pemandangan eksotis.',
                'latitude' => -7.0039,
                'longitude' => 107.2491,
                'status' => 'approved',
                'user_id' => 1,
                'category' => 'Air Terjun',
                'rating' => 4.6,
                'reviews_count' => 140,
                'address' => 'Cianjur Selatan, Kabupaten Bandung, Jawa Barat',
                'image_url' => 'https://picsum.photos/200/300?random=6',
            ],
            [
                'name' => 'Curug Tilu Leuwi Opat',
                'description' => 'Air terjun dengan aliran yang indah, menawarkan trekking dan pemandangan alam yang menyejukkan.',
                'latitude' => -6.7611,
                'longitude' => 107.6023,
                'status' => 'approved',
                'user_id' => 1,
                'category' => 'Air Terjun',
                'rating' => 4.5,
                'reviews_count' => 130,
                'address' => 'Parongpong, Kabupaten Bandung, Jawa Barat',
                'image_url' => 'https://picsum.photos/200/300?random=7',
            ],
            [
                'name' => 'The Lodge Maribaya',
                'description' => 'Resort dengan berbagai aktivitas outdoor seperti berkemah, sky tree, dan wahana foto menarik.',
                'latitude' => -6.7958,
                'longitude' => 107.6641,
                'status' => 'approved',
                'user_id' => 1,
                'category' => 'Resort',
                'rating' => 4.8,
                'reviews_count' => 320,
                'address' => 'Lembang, Kabupaten Bandung, Jawa Barat',
                'image_url' => 'https://picsum.photos/200/300?random=8',
            ],
            [
                'name' => 'Ciwidey Valley Resort',
                'description' => 'Resort dengan pemandangan pegunungan yang asri, dilengkapi dengan fasilitas kolam air panas dan taman bermain anak.',
                'latitude' => -7.1675,
                'longitude' => 107.4089,
                'status' => 'approved',
                'user_id' => 1,
                'category' => 'Resort',
                'rating' => 4.7,
                'reviews_count' => 210,
                'address' => 'Ciwidey, Kabupaten Bandung, Jawa Barat',
                'image_url' => 'https://picsum.photos/200/300?random=9',
            ],
            [
                'name' => 'Taman Hutan Raya Ir. H. Djuanda',
                'description' => 'Kawasan konservasi dengan hutan lebat, gua bersejarah, dan jalur trekking yang menarik untuk wisata edukasi.',
                'latitude' => -6.8575,
                'longitude' => 107.6301,
                'status' => 'approved',
                'user_id' => 1,
                'category' => 'Alam',
                'rating' => 4.6,
                'reviews_count' => 280,
                'address' => 'Dago Pakar, Kabupaten Bandung, Jawa Barat',
                'image_url' => 'https://picsum.photos/200/300?random=10',
            ],
            [
                'name' => 'Orchid Forest Cikole',
                'description' => 'Hutan pinus dengan koleksi anggrek langka, spot foto yang menarik, dan jembatan gantung yang ikonik.',
                'latitude' => -6.7912,
                'longitude' => 107.6137,
                'status' => 'approved',
                'user_id' => 1,
                'category' => 'Rekreasi',
                'rating' => 4.8,
                'reviews_count' => 350,
                'address' => 'Cikole, Lembang, Kabupaten Bandung, Jawa Barat',
                'image_url' => 'https://picsum.photos/200/300?random=11',
            ],
            [
                'name' => 'Dago Dream Park',
                'description' => 'Taman rekreasi dengan berbagai wahana seperti flying fox, perahu terbang, dan spot foto tematik.',
                'latitude' => -6.8322,
                'longitude' => 107.6351,
                'status' => 'approved',
                'user_id' => 1,
                'category' => 'Hiburan',
                'rating' => 4.5,
                'reviews_count' => 290,
                'address' => 'Dago, Kabupaten Bandung, Jawa Barat',
                'image_url' => 'https://picsum.photos/200/300?random=12',
            ],
            [
                'name' => 'Tebing Keraton',
                'description' => 'Destinasi wisata alam dengan pemandangan sunrise dan hamparan hutan yang indah dari ketinggian.',
                'latitude' => -6.8298,
                'longitude' => 107.6452,
                'status' => 'approved',
                'user_id' => 1,
                'category' => 'Alam',
                'rating' => 4.7,
                'reviews_count' => 230,
                'address' => 'Dago Pakar, Kabupaten Bandung, Jawa Barat',
                'image_url' => 'https://picsum.photos/200/300?random=13',
            ],
            [
                'name' => 'Curug Cimahi',
                'description' => 'Air terjun yang menawarkan pemandangan spektakuler dengan lampu warna-warni saat malam hari.',
                'latitude' => -6.8285,
                'longitude' => 107.5793,
                'status' => 'approved',
                'user_id' => 1,
                'category' => 'Air Terjun',
                'rating' => 4.6,
                'reviews_count' => 190,
                'address' => 'Parongpong, Kabupaten Bandung, Jawa Barat',
                'image_url' => 'https://picsum.photos/200/300?random=14',
            ],
            [
                'name' => 'Sapu Lidi Resort',
                'description' => 'Resort dengan suasana pedesaan khas Sunda, menawarkan penginapan unik di tengah sawah dan danau.',
                'latitude' => -6.8083,
                'longitude' => 107.5956,
                'status' => 'approved',
                'user_id' => 1,
                'category' => 'Resort',
                'rating' => 4.5,
                'reviews_count' => 160,
                'address' => 'Lembang, Kabupaten Bandung, Jawa Barat',
                'image_url' => 'https://picsum.photos/200/300?random=15',
            ],
        ];

        foreach ($locations as $location) {
            Location::create($location);
        }
    }
}
